/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRentabilidadRouteImport } from './routes/_authenticated/rentabilidad'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedCartaRouteImport } from './routes/_authenticated/carta'
import { Route as AuthenticatedCartaDishIdRouteImport } from './routes/_authenticated/carta.$dishId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRentabilidadRoute =
  AuthenticatedRentabilidadRouteImport.update({
    id: '/rentabilidad',
    path: '/rentabilidad',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartaRoute = AuthenticatedCartaRouteImport.update({
  id: '/carta',
  path: '/carta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartaDishIdRoute =
  AuthenticatedCartaDishIdRouteImport.update({
    id: '/$dishId',
    path: '/$dishId',
    getParentRoute: () => AuthenticatedCartaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/carta': typeof AuthenticatedCartaRouteWithChildren
  '/compras': typeof AuthenticatedComprasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/rentabilidad': typeof AuthenticatedRentabilidadRoute
  '/carta/$dishId': typeof AuthenticatedCartaDishIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/carta': typeof AuthenticatedCartaRouteWithChildren
  '/compras': typeof AuthenticatedComprasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/rentabilidad': typeof AuthenticatedRentabilidadRoute
  '/carta/$dishId': typeof AuthenticatedCartaDishIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/carta': typeof AuthenticatedCartaRouteWithChildren
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/rentabilidad': typeof AuthenticatedRentabilidadRoute
  '/_authenticated/carta/$dishId': typeof AuthenticatedCartaDishIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/carta'
    | '/compras'
    | '/dashboard'
    | '/inventario'
    | '/onboarding'
    | '/rentabilidad'
    | '/carta/$dishId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/carta'
    | '/compras'
    | '/dashboard'
    | '/inventario'
    | '/onboarding'
    | '/rentabilidad'
    | '/carta/$dishId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/carta'
    | '/_authenticated/compras'
    | '/_authenticated/dashboard'
    | '/_authenticated/inventario'
    | '/_authenticated/onboarding'
    | '/_authenticated/rentabilidad'
    | '/_authenticated/carta/$dishId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rentabilidad': {
      id: '/_authenticated/rentabilidad'
      path: '/rentabilidad'
      fullPath: '/rentabilidad'
      preLoaderRoute: typeof AuthenticatedRentabilidadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carta': {
      id: '/_authenticated/carta'
      path: '/carta'
      fullPath: '/carta'
      preLoaderRoute: typeof AuthenticatedCartaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carta/$dishId': {
      id: '/_authenticated/carta/$dishId'
      path: '/$dishId'
      fullPath: '/carta/$dishId'
      preLoaderRoute: typeof AuthenticatedCartaDishIdRouteImport
      parentRoute: typeof AuthenticatedCartaRoute
    }
  }
}

interface AuthenticatedCartaRouteChildren {
  AuthenticatedCartaDishIdRoute: typeof AuthenticatedCartaDishIdRoute
}

const AuthenticatedCartaRouteChildren: AuthenticatedCartaRouteChildren = {
  AuthenticatedCartaDishIdRoute: AuthenticatedCartaDishIdRoute,
}

const AuthenticatedCartaRouteWithChildren =
  AuthenticatedCartaRoute._addFileChildren(AuthenticatedCartaRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCartaRoute: typeof AuthenticatedCartaRouteWithChildren
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRentabilidadRoute: typeof AuthenticatedRentabilidadRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCartaRoute: AuthenticatedCartaRouteWithChildren,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRentabilidadRoute: AuthenticatedRentabilidadRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
