/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRentabilidadRouteImport } from './routes/_authenticated/rentabilidad'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedComiteRouteImport } from './routes/_authenticated/comite'
import { Route as AuthenticatedAjustesRouteImport } from './routes/_authenticated/ajustes'
import { Route as AuthenticatedFacturasIndexRouteImport } from './routes/_authenticated/facturas.index'
import { Route as AuthenticatedCartaIndexRouteImport } from './routes/_authenticated/carta.index'
import { Route as AuthenticatedFacturasInvoiceIdRouteImport } from './routes/_authenticated/facturas.$invoiceId'
import { Route as AuthenticatedCartaImportarRouteImport } from './routes/_authenticated/carta.importar'
import { Route as AuthenticatedCartaDishIdRouteImport } from './routes/_authenticated/carta.$dishId'
import { Route as ApiPublicHooksCommitteeNightlyRouteImport } from './routes/api/public/hooks/committee-nightly'
import { Route as AuthenticatedCartaImportarImportIdRouteImport } from './routes/_authenticated/carta.importar.$importId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRentabilidadRoute =
  AuthenticatedRentabilidadRouteImport.update({
    id: '/rentabilidad',
    path: '/rentabilidad',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComiteRoute = AuthenticatedComiteRouteImport.update({
  id: '/comite',
  path: '/comite',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAjustesRoute = AuthenticatedAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacturasIndexRoute =
  AuthenticatedFacturasIndexRouteImport.update({
    id: '/facturas/',
    path: '/facturas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCartaIndexRoute = AuthenticatedCartaIndexRouteImport.update({
  id: '/carta/',
  path: '/carta/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacturasInvoiceIdRoute =
  AuthenticatedFacturasInvoiceIdRouteImport.update({
    id: '/facturas/$invoiceId',
    path: '/facturas/$invoiceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCartaImportarRoute =
  AuthenticatedCartaImportarRouteImport.update({
    id: '/carta/importar',
    path: '/carta/importar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCartaDishIdRoute =
  AuthenticatedCartaDishIdRouteImport.update({
    id: '/carta/$dishId',
    path: '/carta/$dishId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksCommitteeNightlyRoute =
  ApiPublicHooksCommitteeNightlyRouteImport.update({
    id: '/api/public/hooks/committee-nightly',
    path: '/api/public/hooks/committee-nightly',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCartaImportarImportIdRoute =
  AuthenticatedCartaImportarImportIdRouteImport.update({
    id: '/$importId',
    path: '/$importId',
    getParentRoute: () => AuthenticatedCartaImportarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/comite': typeof AuthenticatedComiteRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/rentabilidad': typeof AuthenticatedRentabilidadRoute
  '/carta/$dishId': typeof AuthenticatedCartaDishIdRoute
  '/carta/importar': typeof AuthenticatedCartaImportarRouteWithChildren
  '/facturas/$invoiceId': typeof AuthenticatedFacturasInvoiceIdRoute
  '/carta/': typeof AuthenticatedCartaIndexRoute
  '/facturas/': typeof AuthenticatedFacturasIndexRoute
  '/carta/importar/$importId': typeof AuthenticatedCartaImportarImportIdRoute
  '/api/public/hooks/committee-nightly': typeof ApiPublicHooksCommitteeNightlyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/comite': typeof AuthenticatedComiteRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/rentabilidad': typeof AuthenticatedRentabilidadRoute
  '/carta/$dishId': typeof AuthenticatedCartaDishIdRoute
  '/carta/importar': typeof AuthenticatedCartaImportarRouteWithChildren
  '/facturas/$invoiceId': typeof AuthenticatedFacturasInvoiceIdRoute
  '/carta': typeof AuthenticatedCartaIndexRoute
  '/facturas': typeof AuthenticatedFacturasIndexRoute
  '/carta/importar/$importId': typeof AuthenticatedCartaImportarImportIdRoute
  '/api/public/hooks/committee-nightly': typeof ApiPublicHooksCommitteeNightlyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/ajustes': typeof AuthenticatedAjustesRoute
  '/_authenticated/comite': typeof AuthenticatedComiteRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/rentabilidad': typeof AuthenticatedRentabilidadRoute
  '/_authenticated/carta/$dishId': typeof AuthenticatedCartaDishIdRoute
  '/_authenticated/carta/importar': typeof AuthenticatedCartaImportarRouteWithChildren
  '/_authenticated/facturas/$invoiceId': typeof AuthenticatedFacturasInvoiceIdRoute
  '/_authenticated/carta/': typeof AuthenticatedCartaIndexRoute
  '/_authenticated/facturas/': typeof AuthenticatedFacturasIndexRoute
  '/_authenticated/carta/importar/$importId': typeof AuthenticatedCartaImportarImportIdRoute
  '/api/public/hooks/committee-nightly': typeof ApiPublicHooksCommitteeNightlyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ajustes'
    | '/comite'
    | '/compras'
    | '/dashboard'
    | '/inventario'
    | '/marketing'
    | '/onboarding'
    | '/rentabilidad'
    | '/carta/$dishId'
    | '/carta/importar'
    | '/facturas/$invoiceId'
    | '/carta/'
    | '/facturas/'
    | '/carta/importar/$importId'
    | '/api/public/hooks/committee-nightly'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ajustes'
    | '/comite'
    | '/compras'
    | '/dashboard'
    | '/inventario'
    | '/marketing'
    | '/onboarding'
    | '/rentabilidad'
    | '/carta/$dishId'
    | '/carta/importar'
    | '/facturas/$invoiceId'
    | '/carta'
    | '/facturas'
    | '/carta/importar/$importId'
    | '/api/public/hooks/committee-nightly'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/ajustes'
    | '/_authenticated/comite'
    | '/_authenticated/compras'
    | '/_authenticated/dashboard'
    | '/_authenticated/inventario'
    | '/_authenticated/marketing'
    | '/_authenticated/onboarding'
    | '/_authenticated/rentabilidad'
    | '/_authenticated/carta/$dishId'
    | '/_authenticated/carta/importar'
    | '/_authenticated/facturas/$invoiceId'
    | '/_authenticated/carta/'
    | '/_authenticated/facturas/'
    | '/_authenticated/carta/importar/$importId'
    | '/api/public/hooks/committee-nightly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksCommitteeNightlyRoute: typeof ApiPublicHooksCommitteeNightlyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rentabilidad': {
      id: '/_authenticated/rentabilidad'
      path: '/rentabilidad'
      fullPath: '/rentabilidad'
      preLoaderRoute: typeof AuthenticatedRentabilidadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comite': {
      id: '/_authenticated/comite'
      path: '/comite'
      fullPath: '/comite'
      preLoaderRoute: typeof AuthenticatedComiteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajustes': {
      id: '/_authenticated/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAjustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facturas/': {
      id: '/_authenticated/facturas/'
      path: '/facturas'
      fullPath: '/facturas/'
      preLoaderRoute: typeof AuthenticatedFacturasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carta/': {
      id: '/_authenticated/carta/'
      path: '/carta'
      fullPath: '/carta/'
      preLoaderRoute: typeof AuthenticatedCartaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facturas/$invoiceId': {
      id: '/_authenticated/facturas/$invoiceId'
      path: '/facturas/$invoiceId'
      fullPath: '/facturas/$invoiceId'
      preLoaderRoute: typeof AuthenticatedFacturasInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carta/importar': {
      id: '/_authenticated/carta/importar'
      path: '/carta/importar'
      fullPath: '/carta/importar'
      preLoaderRoute: typeof AuthenticatedCartaImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carta/$dishId': {
      id: '/_authenticated/carta/$dishId'
      path: '/carta/$dishId'
      fullPath: '/carta/$dishId'
      preLoaderRoute: typeof AuthenticatedCartaDishIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/committee-nightly': {
      id: '/api/public/hooks/committee-nightly'
      path: '/api/public/hooks/committee-nightly'
      fullPath: '/api/public/hooks/committee-nightly'
      preLoaderRoute: typeof ApiPublicHooksCommitteeNightlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/carta/importar/$importId': {
      id: '/_authenticated/carta/importar/$importId'
      path: '/$importId'
      fullPath: '/carta/importar/$importId'
      preLoaderRoute: typeof AuthenticatedCartaImportarImportIdRouteImport
      parentRoute: typeof AuthenticatedCartaImportarRoute
    }
  }
}

interface AuthenticatedCartaImportarRouteChildren {
  AuthenticatedCartaImportarImportIdRoute: typeof AuthenticatedCartaImportarImportIdRoute
}

const AuthenticatedCartaImportarRouteChildren: AuthenticatedCartaImportarRouteChildren =
  {
    AuthenticatedCartaImportarImportIdRoute:
      AuthenticatedCartaImportarImportIdRoute,
  }

const AuthenticatedCartaImportarRouteWithChildren =
  AuthenticatedCartaImportarRoute._addFileChildren(
    AuthenticatedCartaImportarRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAjustesRoute: typeof AuthenticatedAjustesRoute
  AuthenticatedComiteRoute: typeof AuthenticatedComiteRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRentabilidadRoute: typeof AuthenticatedRentabilidadRoute
  AuthenticatedCartaDishIdRoute: typeof AuthenticatedCartaDishIdRoute
  AuthenticatedCartaImportarRoute: typeof AuthenticatedCartaImportarRouteWithChildren
  AuthenticatedFacturasInvoiceIdRoute: typeof AuthenticatedFacturasInvoiceIdRoute
  AuthenticatedCartaIndexRoute: typeof AuthenticatedCartaIndexRoute
  AuthenticatedFacturasIndexRoute: typeof AuthenticatedFacturasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAjustesRoute: AuthenticatedAjustesRoute,
  AuthenticatedComiteRoute: AuthenticatedComiteRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRentabilidadRoute: AuthenticatedRentabilidadRoute,
  AuthenticatedCartaDishIdRoute: AuthenticatedCartaDishIdRoute,
  AuthenticatedCartaImportarRoute: AuthenticatedCartaImportarRouteWithChildren,
  AuthenticatedFacturasInvoiceIdRoute: AuthenticatedFacturasInvoiceIdRoute,
  AuthenticatedCartaIndexRoute: AuthenticatedCartaIndexRoute,
  AuthenticatedFacturasIndexRoute: AuthenticatedFacturasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksCommitteeNightlyRoute: ApiPublicHooksCommitteeNightlyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
